main = ".open-next/worker.js"
name = "lession1-cloudflare"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
DEEPSEEK_MODEL = "deepseek-chat"

[assets]
directory = ".open-next/assets"
binding = "STATIC_ASSETS"
